
spring:
  profiles:
    active: dev

  mail:
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2212340514@qq.com
    #授权码
    password: mesvlddkvdqgebij
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
